//recruitment
export const QUERYJOBLIST = 'QUERYJOBLIST';
export const RECRUITMENTLIST = 'RECRUITMENTLIST';
export const UPDATERECRUITMENT = 'UPDATERECRUITMENT';
export const UPDATESTATUS = 'UPDATESTATUS';

//message
export const ADDMESSAGE = 'ADDMESSAGE'
export const GETHISTORYMESSAGE = 'GETHISTORYMESSAGE'

export const UPDATEMESSAGE = 'UPDATEMESSAGE'
export const GETUNREADMESSAGE = 'GETUNREADMESSAGE'
export const GETLINKMANS = 'GETLINKMANS'
export const MSGINITIALIZE = 'MSGINITIALIZE'
export const UPDATERECRUITMESSAGE = 'UPDATERECRUITMESSAGE'

//user
export const LOGINSUCCESS = 'LOGINSUCCESS'
export const ONLINE = 'ONLINE'
export const OFFLINE = 'OFFLINE'
export const INITIALIZE = 'INITIALIZE'
export const UPDATEINFO = 'UPDATEINFO'

//ui
export const OPENNOTIFICATION = 'OPENNOTIFICATION'
export const CLOSENOTIFICATION = 'CLOSENOTIFICATION'
