//recruitment
export const QUERYJOBLIST = 'QUERYJOBLIST';
export const RECRUITMENTLIST = 'RECRUITMENTLIST';

//message
export const ADDMESSAGE = 'ADDMESSAGE'
export const GETHISTORYMESSAGE = 'GETHISTORYMESSAGE'
export const UPDATEMESSAGE = 'UPDATEMESSAGE'

//user
export const LOGINSUCCESS = 'LOGINSUCCESS'
export const ONLINE = 'ONLINE'
export const OFFLINE = 'OFFLINE'
export const INITIALIZE = 'INITIALIZE'
export const UPDATEINFO = 'UPDATEINFO'

//ui
export const OPENNOTIFICATION = 'OPENNOTIFICATION'
export const CLOSENOTIFICATION = 'CLOSENOTIFICATION'
